### ISSUE TITLE
README unclear

### ISSUE THREAD

**Issue by VanessaPhippsCfa** [zimfw/asdf#6]
### Is your feature request related to a problem? Please describe.

I'm trying to get into asdf, and direnv, on the promise of no longer having a bunch of different tool version managers. But it's difficult to know where to start, and this README confused me right off the bat. There seem to be two conflicting instructions, one of which relies on doing a "do NOT" line in the other.

You can't

> Make sure the ~/.config/direnv/lib/use_asdf.sh script exists.

Because it is generated by `asdf direnv setup`, which you are told not to do:

> Do not run this command: asdf direnv setup --shell zsh --version latest

In fact, the second set of instructions recommends removing this module, which is an odd thing to do inside a module's README.

> Remove zmodule asdf from .zimrc or any asdf initialization from .zshrc.

### Describe the solution you'd like

Can you separate the instructions for system-installed vs asdf-installed direnv? And explain the reason for the "do NOT" line? And clarify that only the asdf-installed setup does the shim skipping, if I understand correctly?

### Describe alternatives you've considered

- A single, clearer set of instructions with steps that are different based on which direnv being used (splitting them seems clearer)
- Deprecating this module entirely in favor of setting up asdf via direnv (probably overkill)
- Moving the system direnv instructions into the direnv module https://github.com/zimfw/direnv (direnv isn't an asdf-specific thing)

### Additional context

I'm on macOS, using Homebrew for asdf and direnv. I'm not on a team, just trying to keep my own sanity when it comes to tool versions. I'm new to asdf, direnv, and zimfw, but am happy with zimfw so far, this has been my first real hiccup.

**Comment by ericbn** [comment]
Hi @VanessaPhippsCfa. The FAQ has two sections for two different and separate setup options: using direnv installed and managed by asdf (with the direnv plugin) or using a direnv installation outside asdf (with your package manager). Maybe that's not clear, but you do one OR the other.

**Comment by ericbn** [comment]
Maybe the "Do not run this command" step in the first FAQ section is wrong. A good part of the first FAQ section was written by @luong-komorebi and I didn't double check the steps myself.

**Comment by ericbn** [comment]
I was not using asdf anymore, but I've finally tried it out again and fixed the README.md with the instructions for the different suggested setups.

**Comment by luong-komorebi** [comment]
same as me. I am not using asdf anymore

Thank you @ericbn for the fix. I am not sure what happened to my github notification but I just saw this today
